### PR TITLE
Surprise me

### LINKED ISSUE #111: Load a random MUD
Have a "Surprise Me" game picker on the game listing page.

Two modes:
- Surprise Me: Randomly pick an online game and show the profile
- Surprise Me & Play: Randomly pick an online game and launch the web client (only enabled games)

### PR DESCRIPTION
**Pull request by donaldducky**
Closes #111 

Hi @oestrich, taking a stab at this!

I have a few questions:
* Do you use the elixir formatter? I noticed there were "extra" changes when I edited the files but I only committed the actual changes.
* I didn't really find any tests for controllers, does this need some tests to accompany the change?

### CODE REVIEW

**Comment by donaldducky** [comment]
Oh, forgot to mention when I ran `mix ecto.reset` it failed because game needed the `description` field set, so I added a description.

Btw, it looks like the ci process is only running on `push`. Maybe change `on: push` in the github workflows to: `on: [push, pull_request]`?

**Comment by oestrich** [comment]
Ah, nice catch on the PR part for actions. I updated that.

I need to just bite the bullet and run the formatter on everything and enforce it going forward. I've mostly been running it on single files as I work on them to keep the change low.

I don't tend to do a lot of tests for controllers, keeping those thin and calling something deeper. I would probably move the controller code you added as private functions to `Grapevine.Games`. I tend to test the context/data layer instead of controllers. This is pretty low risk for failing so I'm not worried about controller tests for this. Looks good overall!

If you could move the private functions into `Grapevine.Games` as the same names but public I'll merge this. Thanks for the PR!

**Comment by donaldducky** [comment]
Cool, I felt funny leaving those private functions in the controller but I have another question about that.

Do you think it makes sense to move the call to `Grapevine.Presence.online_games/0` into `Grapevine.Games`? I didn't put it in there originally because I didn't see any usages of `Grapevine.Presence` inside there.

re: PR, no problem! Thanks for your work in the community!

**Comment by oestrich** [comment]
Hmm, it might make more sense to move into `Grapevine.Presence` then. You have a good point. Let's move there instead. 👍

**Comment by donaldducky** [comment]
Cool, the ci ran 👯

**Review by oestrich — APPROVED** [review]
:shipit: Thanks!

**Pull request merged**
