### PR TITLE
Create games list in settings sidebar

### PR DESCRIPTION
**Pull request by carlism**
I'm looking to fulfill the issue #101 

I'd like to get some feedback as to whether this is the sort of change imagined.

Thanks

### CODE REVIEW

**Comment by oestrich** [comment]
Yeah, this looks pretty spot on! The only other thing I'd want to do is stick the sidebar on the `manage/games#show` page as it looks weird without it now. Let me know if you want to add that or I can. Either way this looks good to go. Thanks for the contribution!

**Comment by carlism** [comment]
I wasn’t sure that page shouldn’t go away altogether as there aren’t links to it now.   I’ll add it there for now. No worries

**Comment by carlism** [comment]
Oh #show!  I read that as games#index, my bad.  You want the sidebar in games#show?  That seems a bit odd with the hero image and all.

**Comment by oestrich** [comment]
Hmm, good point. Let's stick with this as is and I'll stew on the other part. Thanks again!

**Comment by oestrich** [comment]
Fixes #101

**Pull request merged**
